### PR TITLE
Add BETTER_ENUMS_IGNORE_ATTRIBUTES_* for clang

### PR DESCRIPTION
**Pull request by janten**

### CODE REVIEW

**Comment by janten** [comment]
The build errors in Travis CI seem to be unrelated to the change here. Could you check this, @aantron?

**Comment by aantron** [comment]
@janten Thanks. Yes, the Travis errors are unrelated, and we should ignore them :) I should probably disable Travis for now, as I don't have time to fix this the "right" way at the moment.

Can you say what error this PR addresses? These macros were added because a GCC version had broken handling of `-Wattributes` (#79). Is there a similar problem with some versions of Clang?

**Comment by janten** [comment]
I am using Xcode 11.3 and was getting warnings about `BETTER_ENUMS_IGNORE_ATTRIBUTES_BEGIN` being undefined, which I fixed here. A previous version of Better Enums, which did not have `BETTER_ENUMS_IGNORE_ATTRIBUTES_BEGIN` all, also worked fine.

**Comment by aantron** [comment]
Thanks. I think these macros should be defined to expand to nothing on Clang. Can you try that?

**Comment by janten** [comment]
It works with empty #defines, too. I updated the source accordingly.

**Comment by aantron** [comment]
Thanks again!

**Pull request merged**
