### PR TITLE
Add macro for adding attributes to enum class

### PR DESCRIPTION
**Pull request by michaelernst**
I think this would be a nice extension to the current framework. It is possible to add as many attributes as you like, e.g. an annotation().

In case the macro is not defined it will be defined without having any function / impact on existing code.

In our case we would like to use it for annotating better enum classes and be able to identify the classes later in a CASTXML generated document.

### CODE REVIEW

**Comment by michaelernst** [comment]
Tests seem to fail because of errors setting up the test system

**Comment by aantron** [comment]
Could you try moving the conditional definition of `BETTER_ENUMS_CLASS_ATTRIBUTE` to before line 622 to try to fix https://ci.appveyor.com/project/aantron/better-enums/builds/29345504/job/xs1mff9vs06epn50#L938?

**Comment by michaelernst** [comment]
Ah, I thougth that this might be a problem. With VS 2019 and clang it was working fine and I thought its nicer being with the user defined macros.

I moved the definition above the class declaration, if you have a specific place you would like the macro being placed - let me know.

**Comment by aantron** [comment]
Thanks!

**Pull request merged**
